### PR TITLE
Fix #153 Cover image doesn't show up with epub in iBooks

### LINKED ISSUE #153: Cover image doesn't show up with epub in iBooks
The cover image doesn't show up for the epub in iBooks.

### PR DESCRIPTION
**Pull request by iwazaru**
iBooks needs the following meta tag:

    <meta name="cover" content="image.cover.png" />

in `content.opf` in order to display the cover.

Fixes #153

### CODE REVIEW

**Comment by marijnh** [comment]
Shouldn't that point at `img/cover.png` instead?

**Comment by iwazaru** [comment]
You're absolutely right. I fixed that.

**Comment by marijnh** [comment]
Thanks. Merged. The epub on the website is in the process of being rebuilt.

**Comment by esparkman** [comment]
I still see the issue when downloading the ePub from the website and load it into iBooks.

**Comment by marijnh** [comment]
Is the meta tag there when you unzip the book? It should be. If it doesn't help, the problem diagnosis may have been wrong in the first place?

**Comment by esparkman** [comment]
I'll verify. One sec.

**Comment by esparkman** [comment]
Line 75:     <item id="image.cover.png" href="img/cover.png" media-type="image/png"/>

**Comment by marijnh** [comment]
Could you clarify?

**Comment by esparkman** [comment]
That is on Line 75 of the content.opf. When I manually pulled and compiled the file it worked just fine.

**Comment by iwazaru** [comment]
My bad. I think I was right in the first place. Attribute `name` value should be the id of the image as defined in the manifest `item` tag and not the image path, so:

    <meta name="cover" content="image.cover.png" />

was indeed correct.

**Pull request merged**
