### PR TITLE
How about make PDF headings more "eloquent"?

### PR DESCRIPTION
**Pull request by skotniczny**

### CODE REVIEW

**Comment by marijnh** [comment]
Thank you! Looks great. Merged as 2a55870

Do you by any chance know what the cleanest way to insert the cover picture as a full page image at the start of the book would be?

**Comment by skotniczny** [comment]
The easiest way will be to use the package '[pdfpages](https://ctan.org/pkg/pdfpages)'; please export the cover as a .pdf (however the pdf is in A4 and the cover of your book is US Letter size).

**Comment by marijnh** [comment]
I'll give it a shot, thanks.

**Comment by skotniczny** [comment]
Even `\includepdf{../img/cover.jpg}` inserted after `\begin{document}` roughly works.

**Comment by marijnh** [comment]
Oh, right, that's easy. With a yellow background that's an okay cover page. See a64b79c

**Comment by skotniczny** [comment]
I like it and prefer than switching to US Letter

I noticed three minor bugs ([because of bidi](https://github.com/tex-xet/bidi/issues/50))

- wrong chapters font in TOC,
- more space after listings, what finally causes few more pages,
- impossible to set font for author at tittle page.

Please ignore this for your sanity.

**Comment by marijnh** [comment]
> Please ignore this for your sanity.

Yeah, I think that's a good idea.

**Pull request closed without merging**
