### PR TITLE
Make preformatted text wrap

### PR DESCRIPTION
**Pull request by skotniczny**
Issue #174

Also font-size respect the user's font settings.

### CODE REVIEW

**Comment by marijnh** [comment]
Thanks. Why did you drop the media query? I think having a smaller font is generally preferable to having code wrap, which tends to make it hard to read.

**Comment by skotniczny** [comment]
I assume that readers can change the font size on their devices, and the difference between 20 px regular text and 10 px pre text seems too big for me.

[20 px regular, 14 px pre vs 20 px regular, 10 px pre]
calibre

However, I thought about it and fixed it a bit. It looks quite good, I attach few screenshots from my devices.

[Kindle 7 portrait](https://user-images.githubusercontent.com/15799058/37053472-8cb89624-217c-11e8-8715-3b54ca87839a.png), [Kindle 7 landscape](https://user-images.githubusercontent.com/15799058/37053473-8cde99d2-217c-11e8-82b1-f356d44da65e.png), [Paperwhite 3 portrait](https://user-images.githubusercontent.com/15799058/37056481-d98c628e-2184-11e8-9078-8903d902af43.png), [Paperwhite 3 landscape](https://user-images.githubusercontent.com/15799058/37056505-ecf00a24-2184-11e8-83e8-4d9824329643.png)

**Comment by marijnh** [comment]
I agree that looks good. I'm using a max line length of 61 characters in the examples—does the 35em in the query cause the font to shrink at about the point where such a line becomes too long on typical default font sizes?

**Comment by skotniczny** [comment]
I use this value because at eloquentjavascript.net article max-width is 35 em (pre text font-size in e-book is 80%, but it assumes some default margins around page). There are screenshots of long lines: [Paperwhite portrait](https://user-images.githubusercontent.com/15799058/37058868-26bcbfde-218c-11e8-838e-665286ed6472.png), [Kindle 7 portrait](https://user-images.githubusercontent.com/15799058/37059127-e56b4f04-218c-11e8-94be-dc80d3830338.png), [Kindle 7 landscape](https://user-images.githubusercontent.com/15799058/37059122-e32b02d4-218c-11e8-8117-ab88b7325192.png)

**Comment by marijnh** [comment]
The lines are wrapped in the Kindle 7 portrait screenshot—there's a lot of lines at or near the max length in the book, it'd be nice if they didn't wrap on popular platforms. Maybe just reduce the font size by another 5%?

**Comment by skotniczny** [comment]
I would prefer the reader decrease font size ([size "2" setted, pre 70%](https://user-images.githubusercontent.com/15799058/37064507-8067773e-219d-11e8-808a-aa55c2b5c822.png)), but I understand your point, 65 percent is still better than 50.

Default font size, pre 65%:
screenshot_2018_03_07t01_06_28 0159

**Comment by marijnh** [comment]
Wonderful. Merged as 6bd984f7ca05...3f0e331ea359

**Comment by skotniczny** [comment]
Finally, we stayed at 70%, because I didn't push the last change, but I looked at it again and I found such small (65%) font on 6-inch e-ink display was unreadable and that's why in my opinion it's better to break lines.

**Comment by marijnh** [comment]
Fair enough. I guess people can turn usually their devices if the wrapped lines bother them.

**Pull request closed without merging**
