### PR TITLE
Shorter regex for problem 7.

### PR DESCRIPTION
**Pull request by jtmcgrath**
Hey, not sure if this is right since I'm pretty new to regexp, but it looks like my solution for this one is shorter. Would be great to know if I've made a mistake or not!

Loving the book so far, it's absolutely brilliant.

### CODE REVIEW

**Comment by marijnh** [comment]
Nice, but this will count characters like `!` or `—` as part of a word, which I'd say is a bug.

**Comment by jtmcgrath** [comment]
Ahh that makes sense, thanks. Would there be a similar problem with this: `\b[^\We]+\b`?

**Comment by marijnh** [comment]
That looks like it works! Do you want to update the pull request with this solution?

**Comment by jtmcgrath** [comment]
Done - not sure why the commit didn't show up in this PR automatically - maybe because I don't have it in a branch? Created a new PR anyway!

**Pull request closed without merging**
