### PR TITLE
Fix Latex compilation errors

### PR DESCRIPTION
**Pull request by skotniczny**
It seems to work almost well

### CODE REVIEW

**Comment by skotniczny** [comment]
Notice that compilation fails after apple emoji in the line: "The problem is that the 🍎 in the first line is treated as two code"

**Comment by skotniczny** [comment]
Please compile document with this line, it will be clear.
`\defaultfontfeatures[\emojifont]{Color=FF0000,Scale=1.15,FakeBold=1.25}`

**Comment by marijnh** [comment]
Where should I look for the problem? The apple example and the mixed script one still look the same with that line added.

**Comment by skotniczny** [comment]
Look, after apple emoji - font size, quotation marks and dashes are broken

screenshot-2018-2-14 eloquent_javascript pdf

screenshot-2018-2-14 eloquent_javascript pdf 1

**Comment by marijnh** [comment]
Still not sure what you mean. In trying to build with your changes, but am getting font errors. What way of installing FandolSong and CMU Serif do you recommend?

**Comment by skotniczny** [comment]
Try with direct path, for exapmple `\newfontface{\emojifont}{Symbola_hint.ttf}[Path=/usr/share/fonts/truetype/ancient-scripts/]`

**Comment by marijnh** [comment]
Ohh, I see what you mean now, after that point all quotes are messed up. That's awful. Trying to find a chinese font that actually works now.

**Comment by marijnh** [comment]
Tried some fonts, but they all look worse than what I had before. What are the reasons for the changes to the handling of the Chinese text?

**Comment by skotniczny** [comment]
I guess, because now it work without errors. :( For example images also works even bad syntax for \usepackage{graphic**S**}

**Comment by marijnh** [comment]
Right. Errors or not, I've reverted a few changes to make the Chinese text look better, and merged the rest of your changes. Thanks for helping out with this! I'm quite clueless when it comes to LaTeX.

**Comment by marijnh** [comment]
Oh, it seems that now the balloon emoji is screwing up all text after it. This is great.

**Comment by marijnh** [comment]
And that is indeed caused by the changes I made to the CJK font handling... which is bizarre, since the problem is a long way from the Chinese characters.

**Comment by skotniczny** [comment]
To save your time, I am attaching pdf with my results of fighting with latex
[book.pdf](https://github.com/marijnh/Eloquent-JavaScript/files/1725908/book.pdf)

**Comment by skotniczny** [comment]
I recommend use Inconsolata LGC, it helps handling with Cyrillic and Greek letters (Chapter 8)

**Comment by skotniczny** [comment]
Definitely it is not case better or worse looking fonts, they look like that because when compilation pass properly latex set it monospaced at any cost. When compilation fails, font are displayed in normal manner.

**Comment by marijnh** [comment]
Using Inconsolata LGC does simplify things a bit. For some reason (doesn't seem to be the font's fault) the Greek letters get a bigger letter spacing even though they are using the same font, so that's not looking great, but I don't care too much.

In patch 5dabfda47f I also changed to an approach where I leave `lst` for Chinese, Arabic, and emoji text, since it seemed to be impossible to get those to render in a good looking way in listings. The result looks better (but is rather fragile).

There's still a bunch of errors in the log that I don't understand, but the output look okay.

**Comment by skotniczny** [comment]
Try add π φ φ ≈,
```
\usepackage{newunicodechar}
\newunicodechar{π}{$\pi$}
\newunicodechar{ϕ}{$\varphi$}
\newunicodechar{≈}{$\approx$}
\newunicodechar{β}{\ss}
```

**Comment by marijnh** [comment]
Oh, good point, added in eb33c5d

**Pull request closed without merging**
