### PR TITLE
--epub option provides a book version

### PR DESCRIPTION
**Pull request by skotniczny**
I'm not entirely sure of your intentions.

### CODE REVIEW

**Comment by marijnh** [comment]
Ahh, good point. Merged!

**Comment by skotniczny** [comment]
Please remember about hints chapter

```html 
consider reading the hints at the <a href="hints">end of the book</a>
```

**Comment by marijnh** [comment]
What do you mean by remembering about the hints chapter?

**Comment by skotniczny** [comment]
`<a href="hints">` this points to nothing

**Comment by marijnh** [comment]
Ahh, I see what you mean now. Done in ed8b01e

**Pull request merged**
