### PR TITLE
Refactor Grid forEach to use get method in Chapter 7

### PR DESCRIPTION
**Pull request by tiago**
* Encapsulate access to the space array.

### CODE REVIEW

**Comment by marijnh** [comment]
This does remove the duplication of the index formula, but at the cost of an extra variable and allocating an object even for null fields. I don't think it's a big enough improvement to merge.

**Comment by tiago** [comment]
The intent of this change was not to remove duplication but to avoid breaking the assumption that data representation is not important, given that reads and writes are encapsulated. And we're breaking it just for the sake of performance. But, fair enough, I guess we can argue both ways.
Thank you for your comments.

**Comment by marijnh** [comment]
Note that this method is part of the `Grid` prototype -- it should be considered to exist _inside_ the encapsulation for this type.

**Comment by tiago** [comment]
Yup, you're right. Thanks.

**Pull request closed without merging**
