### PR TITLE
createTextNode

### PR DESCRIPTION
**Pull request by naduda**
Replace "child" to "new String(child)" for correct presentation cyrillic text.

### CODE REVIEW

**Comment by naduda** [comment]
Replace "child" to "new String(child)" for correct presentation cyrillic text.

**Comment by marijnh** [comment]
Why would that help?

**Comment by naduda** [comment]
You can check for example this - elt('span', null,'Текст'); - and you will
see differences between versions.

2015-05-14 16:07 GMT+03:00 Marijn Haverbeke <notifications@github.com>:

**Comment by naduda** [comment]
If exist the more better way (more right way), please tell me about it.

2015-05-14 16:11 GMT+03:00 Pavlo Naduda <naduda.pr@gmail.com>:

**Comment by marijnh** [comment]
Passing `null` as an argument here will break the example, so I'm really not sure what you are trying to do.

**Pull request closed without merging**
